### ISSUE TITLE
Rename `.env.local.default` to `.env.local.example`

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/vortex#1398]
The purpose of this file is to provide example values for a `.env.local` file that can be used locally by a developer. A consumer project may put more variables and values into this file as needed.

There were some questions raised around `.env.local.default` vs `.env.local.example` as `default` means some sort of "default values" and that this file is **being read by the stack** (but it is not in reality).

The proposal is to rename `.env.local.default` to `.env.local.example` for clarity.

**Comment by richardgaunt** [comment]
Yes I agree, This does improve the communication of the purpose of the file, I think I had become blinded to its ambiguity with use.
